# Generated by Django 6.0 on 2025-12-22 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('uncategorized', 'Sin categoría'), ('music', 'Música'), ('art', 'Arte'), ('video', 'Video'), ('writing', 'Escritos'), ('games', 'Juegos')], default='uncategorized', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/thumbnails/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
