# Generated by Django 6.0 on 2025-12-22 01:18

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True)),
                ('username_display', models.CharField(blank=True, max_length=24, validators=[accounts.validators.validate_username])),
                ('country', models.CharField(blank=True, choices=[('AR', 'Argentina'), ('UY', 'Uruguay'), ('CL', 'Chile'), ('BR', 'Brasil')], max_length=2, null=True)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
